<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GenreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $data = [

        //     "(Classical) Orchestral",
        //     "(Jazz) Latin Jazz",
        //     "(Rock) Singer/Songwriter",
        //     "Acoustic Blues",
        //     "Adult Alternative",
        //     "Adult Contemporary",
        //     "African",
        //     "African Dancehall",
        //     "African Reggae",
        //     "Afrikaans",
        //     "Afro House",
        //     "Afro Soul",
        //     "Afro-Beat",
        //     "Afro-Pop",
        //     "Afro-folk",
        //     "Afro-fusion",
        //     "Afrobeats",
        //     "Alte",
        //     "Alternative",
        //     "Alternative &amp; Rock in Spanish",
        //     "Alternative Country",
        //     "Alternative Folk",
        //     "Alternative Rap",
        //     "Amapiano",
        //     "Ambient",
        //     "American Trad Rock",
        //     "Americana",
        //     "Anime",
        //     "Arabesque",
        //     "Arabic",
        //     "Arabic Pop",
        //     "Arena Rock",
        //     "Art Song",
        //     "Asia",
        //     "Assamese",
        //     "Australia",
        //     "Avant-Garde",
        //     "Avant-Garde Jazz",
        //     "Axé",
        //     "Baile Funk",
        //     "Baladas y Boleros",
        //     "Baroque Era",
        //     "Bass",
        //     "Bebop",
        //     "Benga",
        //     "Bengali",
        //     "Bhojpuri",
        //     "Big Band",
        //     "Bluegrass",
        //     "Blues",
        //     "Blues-Rock",
        //     "Bolero",
        //     "Bollywood",
        //     "Bongo-Flava",
        //     "Bossa Nova",
        //     "Brass &amp; Woodwinds",
        //     "Brazilian",
        //     "Breakbeat",
        //     "British Invasion",
        //     "Britpop",
        //     "CCM",
        //     "Cajun",
        //     "Calypso",
        //     "Cantata",
        //     "Cantopop",
        //     "Caribbean",
        //     "Carnatic Classical",
        //     "Cello",
        //     "Celtic",
        //     "Celtic Folk",
        //     "Chachacha",
        //     "Chamber Music",
        //     "Chant",
        //     "Chanukah",
        //     "Chicago Blues",
        //     "Children's Music",
        //     "Chinese",
        //     "Chinese Alt",
        //     "Chinese Classical",
        //     "Chinese Flute",
        //     "Chinese Hip-Hop",
        //     "Chinese Opera",
        //     "Chinese Orchestral",
        //     "Chinese Regional Folk",
        //     "Chinese Rock",
        //     "Chinese Strings",
        //     "Choral",
        //     "Choro",
        //     "Christian &amp; Gospel",
        //     "Christian Metal",
        //     "Christian Pop",
        //     "Christian Rap",
        //     "Christian Rock",
        //     "Christmas",
        //     "Christmas: Children's",
        //     "Christmas: Classic",
        //     "Christmas: Classical",
        //     "Christmas: Country",
        //     "Christmas: Jazz",
        //     "Christmas: Modern",
        //     "Christmas: Pop",
        //     "Christmas: R&amp;B",
        //     "Christmas: Religious",
        //     "Christmas: Rock",
        //     "Classic Blues",
        //     "Classic Christian",
        //     "Classic/Modern Dancehall",
        //     "Classical",
        //     "Classical Crossover",
        //     "Classical Era",
        //     "College Rock",
        //     "Comedy",
        //     "Contemporary Bluegrass",
        //     "Contemporary Blues",
        //     "Contemporary Celtic",
        //     "Contemporary Country",
        //     "Contemporary Era",
        //     "Contemporary Folk",
        //     "Contemporary Gospel",
        //     "Contemporary Jazz",
        //     "Contemporary Latin",
        //     "Contemporary R&amp;B",
        //     "Contemporary Singer/Songwriter",
        //     "Cool",
        //     "Country",
        //     "Country Blues",
        //     "Country Gospel",
        //     "Coupé-Décalé",
        //     "Crossover Jazz",
        //     "Cuban",
        //     "Dabke",
        //     "Dance",
        //     "Dangdut",
        //     "Death Metal/Black Metal",
        //     "Delta Blues",
        //     "Devotional &amp; Spiritual",
        //     "Dini",
        //     "Dirty South",
        //     "Disco",
        //     "Disney",
        //     "Dixieland",
        //     "Doo Wop",
        //     "Downtempo",
        //     "Dub",
        //     "Dubstep",
        //     "EMO",
        //     "Early Music",
        //     "East Coast Rap",
        //     "Easter",
        //     "Easy Listening",
        //     "Egyptian Hip-Hop",
        //     "Egyptian Pop",
        //     "Egyptian Tarab",
        //     "Electric Blues",
        //     "Electro-Cha'abi",
        //     "Electronic",
        //     "Electronica",
        //     "Enka",
        //     "Europe",
        //     "Fado",
        //     "Fantezi",
        //     "Farsi",
        //     "Film Soundtrack",
        //     "Fitness &amp; Workout",
        //     "Flamenco",
        //     "Folk",
        //     "Folk-Rock",
        //     "Foreign Cinema",
        //     "Forró",
        //     "France",
        //     "French Pop",
        //     "Frevo",
        //     "Funk",
        //     "Fusion",
        //     "Gangsta Rap",
        //     "Garage",
        //     "German Folk",
        //     "German Pop",
        //     "Ghazals",
        //     "Glam Rock",
        //     "Gospel",
        //     "Goth Rock",
        //     "Gqom",
        //     "Grunge",
        //     "Guajira",
        //     "Guaracha",
        //     "Guitar",
        //     "Gujarati",
        //     "Hair Metal",
        //     "Halk",
        //     "Halloween",
        //     "Hard Bop",
        //     "Hard Rock",
        //     "Hardcore",
        //     "Hardcore Rap",
        //     "Haryanvi",
        //     "Hawaii",
        //     "Healing",
        //     "Heavy Metal",
        //     "Highlife",
        //     "Hindustani Classical",
        //     "Hip Hop/Rap",
        //     "Hip-Hop",
        //     "Holiday",
        //     "Honky Tonk",
        //     "House",
        //     "Hörspiele",
        //     "IDM/Experimental",
        //     "Iberia",
        //     "Impressionist",
        //     "Indian",
        //     "Indian Classical",
        //     "Indian Folk",
        //     "Indian Pop",
        //     "Indie Egyptian",
        //     "Indie Levant",
        //     "Indie Maghreb",
        //     "Indie Pop",
        //     "Indie Rock",
        //     "Indo Pop",
        //     "Indonesian Religious",
        //     "Industrial",
        //     "Inspirational",
        //     "Instrumental",
        //     "Iraqi Folk",
        //     "Iraqi Pop",
        //     "Iraqi Tarab",
        //     "Islamic",
        //     "Israeli",
        //     "J-Pop",
        //     "Jam Bands",
        //     "Japan",
        //     "Jazz",
        //     "Jungle/Drum'n'bass",
        //     "K-Pop",
        //     "Kannada",
        //     "Karaoke",
        //     "Kayokyoku",
        //     "Khaleeji",
        //     "Khaleeji Folk",
        //     "Khaleeji Hip-Hop",
        //     "Khaleeji Jalsat",
        //     "Khaleeji Pop",
        //     "Khaleeji Shailat",
        //     "Khaleeji Tarab",
        //     "Kizomba",
        //     "Klezmer",
        //     "Korean",
        //     "Korean Folk-Pop",
        //     "Korean Hip-Hop",
        //     "Korean Indie",
        //     "Korean Rock",
        //     "Korean Traditional",
        //     "Kuduro",
        //     "Kwaito",
        //     "Latin",
        //     "Latin Jazz",
        //     "Latin Rap",
        //     "Levant",
        //     "Levant Electronic",
        //     "Levant Hip-Hop",
        //     "Levant Pop",
        //     "Lounge",
        //     "Lovers Rock",
        //     "Lullabies",
        //     "MPB",
        //     "Maghreb Dance",
        //     "Maghreb Electronic",
        //     "Maghreb Hip-Hop",
        //     "Maghreb Pop",
        //     "Maghreb Rai",
        //     "Mainstream Jazz",
        //     "Malayalam",
        //     "Malaysian Pop",
        //     "Mambo",
        //     "Mandopop",
        //     "Manilla Sound",
        //     "Marathi",
        //     "Marching Bands",
        //     "Maskandi",
        //     "Mbalax",
        //     "Medieval Era",
        //     "Meditation",
        //     "Minimalism",
        //     "Modern Era",
        //     "Motown",
        //     "Musicals",
        //     "Nature",
        //     "Ndombolo",
        //     "Neo-Soul",
        //     "New Acoustic",
        //     "New Age",
        //     "New Wave",
        //     "North African",
        //     "North America",
        //     "Novelty",
        //     "Odia",
        //     "Old School Rap",
        //     "Oldies",
        //     "Opera",
        //     "Oratorio",
        //     "Orchestral",
        //     "Original Pilipino Music",
        //     "Original Score",
        //     "Outlaw Country",
        //     "Pagode",
        //     "Percussion",
        //     "Piano",
        //     "Pinoy Pop",
        //     "Polka",
        //     "Pop",
        //     "Pop Punk",
        //     "Pop in Spanish",
        //     "Pop/Rock",
        //     "Praise &amp; Worship",
        //     "Prog-Rock/Art Rock",
        //     "Psychedelic",
        //     "Punjabi",
        //     "Punjabi Pop",
        //     "Punk",
        //     "R&amp;B/Soul",
        //     "Rabindra Sangeet",
        //     "Ragtime",
        //     "Raices",
        //     "Rajasthani",
        //     "Rap",
        //     "Reggae",
        //     "Reggaeton / Latin Urban",
        //     "Regional Indian",
        //     "Regional Mexicano",
        //     "Relaxation",
        //     "Religious",
        //     "Renaissance",
        //     "Rock",
        //     "Rock &amp; Roll",
        //     "Rockabilly",
        //     "Romantic Era",
        //     "Roots Reggae",
        //     "Roots Rock",
        //     "Russian",
        //     "Russian Bard",
        //     "Russian Chanson",
        //     "Russian Hip-Hop",
        //     "Russian Pop",
        //     "Russian Rock",
        //     "Russian Romance",
        //     "Sacred",
        //     "Salsa y Tropical",
        //     "Samba",
        //     "Sanat",
        //     "Sertanejo",
        //     "Shangaan Electro",
        //     "Shows",
        //     "Sing-Along",
        //     "Singer/Songwriter",
        //     "Ska",
        //     "Smooth Jazz",
        //     "Soca",
        //     "Soft Rock",
        //     "Solo Instrumental",
        //     "Son",
        //     "Soukous",
        //     "Soul",
        //     "Sound Effects",
        //     "Soundtrack",
        //     "South Africa",
        //     "South America",
        //     "Southern Gospel",
        //     "Southern Rock",
        //     "Spoken Word",
        //     "Standards",
        //     "Standup Comedy",
        //     "Stories",
        //     "Sufi",
        //     "Surf",
        //     "Swing",
        //     "TV Soundtrack",
        //     "Taarab",
        //     "Tai-Pop",
        //     "Taiwanese Folk",
        //     "Tamil",
        //     "Tango",
        //     "Tarab",
        //     "Techno",
        //     "Teen Pop",
        //     "Telugu",
        //     "Tex-Mex",
        //     "Thai Country",
        //     "Thai Pop",
        //     "Thanksgiving",
        //     "Tibetan Native Music",
        //     "Timba",
        //     "Trad Jazz",
        //     "Traditional Bluegrass",
        //     "Traditional Celtic",
        //     "Traditional Country",
        //     "Traditional Folk",
        //     "Traditional Gospel",
        //     "Traditional Pop",
        //     "Trance",
        //     "Travel",
        //     "Trot",
        //     "Turkish",
        //     "Turkish Alternative",
        //     "Turkish Hip-Hop/Rap",
        //     "Turkish Pop",
        //     "Turkish Rock",
        //     "UK Hip Hop",
        //     "Underground Rap",
        //     "Urban Cowboy",
        //     "Urdu",
        //     "Video Game",
        //     "Violin",
        //     "Vocal",
        //     "Vocal Jazz",
        //     "Vocal Pop",
        //     "Wedding Music",
        //     "West Coast Rap",
        //     "World",
        //     "Worldbeat",
        //     "Yoga",
        //     "Zouglou",
        //     "Zydeco",
        //     "Özgün",

        // ];
        // foreach($data as $g){
        //     DB::table('only_genres')->insert([
        //         ''
        //     ])
        // }
       
    }
}
