<?php
return [
    'countries' =>
    [
        'AF' => 'Afghanistan',
        'AX' => 'Aland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua And Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia And Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, Democratic Republic',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'Cote D\'Ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island & Mcdonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic Of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle Of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KR' => 'Korea',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Lao People\'s Democratic Republic',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libyan Arab Jamahiriya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia, Federated States Of',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'AN' => 'Netherlands Antilles',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territory, Occupied',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barthelemy',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts And Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin',
        'PM' => 'Saint Pierre And Miquelon',
        'VC' => 'Saint Vincent And Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome And Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia And Sandwich Isl.',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard And Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad And Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks And Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UM' => 'United States Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela',
        'VN' => 'Viet Nam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Islands, U.S.',
        'WF' => 'Wallis And Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    ],

    'genres' => [
        1 => "(Classical) Orchestral",
        2 => "(Jazz) Latin Jazz",
        3 => "(Rock) Singer/Songwriter",
        4 => "Acoustic Blues",
        5 => "Adult Alternative",
        6 => "Adult Contemporary",
        7 => "African",
        8 => "African Dancehall",
        9 => "African Reggae",
        10 => "Afrikaans",
        11 => "Afro House",
        12 => "Afro Soul",
        13 => "Afro-Beat",
        14 => "Afro-Pop",
        15 => "Afro-folk",
        16 => "Afro-fusion",
        17 => "Afrobeats",
        18 => "Alte",
        19 => "Alternative",
        20 => "Alternative & Rock in Spanish",
        21 => "Alternative Country",
        22 => "Alternative Folk",
        23 => "Alternative Rap",
        24 => "Amapiano",
        25 => "Ambient",
        26 => "American Trad Rock",
        27 => "Americana",
        28 => "Anime",
        29 => "Arabesque",
        30 => "Arabic",
        31 => "Arabic Pop",
        32 => "Arena Rock",
        33 => "Art Song",
        34 => "Asia",
        35 => "Assamese",
        36 => "Australia",
        37 => "Avant-Garde",
        38 => "Avant-Garde Jazz",
        39 => "Axé",
        40 => "Baile Funk",
        41 => "Baladas y Boleros",
        42 => "Baroque Era",
        43 => "Bass",
        44 => "Bebop",
        45 => "Benga",
        46 => "Bengali",
        47 => "Bhojpuri",
        48 => "Big Band",
        49 => "Bluegrass",
        50 => "Blues",
        51 => "Blues-Rock",
        52 => "Bolero",
        53 => "Bollywood",
        54 => "Bongo-Flava",
        55 => "Bossa Nova",
        56 => "Brass & Woodwinds",
        57 => "Brazilian",
        58 => "Breakbeat",
        59 => "British Invasion",
        60 => "Britpop",
        61 => "CCM",
        62 => "Cajun",
        63 => "Calypso",
        64 => "Cantata",
        65 => "Cantopop",
        66 => "Caribbean",
        67 => "Carnatic Classical",
        68 => "Cello",
        69 => "Celtic",
        70 => "Celtic Folk",
        71 => "Chachacha",
        72 => "Chamber Music",
        73 => "Chant",
        74 => "Chanukah",
        75 => "Chicago Blues",
        76 => "Children's Music",
        77 => "Chinese",
        78 => "Chinese Alt",
        79 => "Chinese Classical",
        80 => "Chinese Flute",
        81 => "Chinese Hip-Hop",
        82 => "Chinese Opera",
        83 => "Chinese Orchestral",
        84 => "Chinese Regional Folk",
        85 => "Chinese Rock",
        86 => "Chinese Strings",
        87 => "Choral",
        88 => "Choro",
        89 => "Christian & Gospel",
        90 => "Christian Metal",
        91 => "Christian Pop",
        92 => "Christian Rap",
        93 => "Christian Rock",
        94 => "Christmas",
        95 => "Christmas: Children's",
        96 => "Christmas: Classic",
        97 => "Christmas: Classical",
        98 => "Christmas: Country",
        99 => "Christmas: Jazz",
        100 => "Christmas: Modern",
        101 => "Christmas: Pop",
        102 => "Christmas: R&B",
        103 => "Christmas: Religious",
        104 => "Christmas: Rock",
        105 => "Classic Blues",
        106 => "Classic Christian",
        107 => "Classic/Modern Dancehall",
        108 => "Classical",
        109 => "Classical Crossover",
        110 => "Classical Era",
        111 => "College Rock",
        112 => "Comedy",
        113 => "Contemporary Bluegrass",
        114 => "Contemporary Blues",
        115 => "Contemporary Celtic",
        116 => "Contemporary Country",
        117 => "Contemporary Era",
        118 => "Contemporary Folk",
        119 => "Contemporary Gospel",
        120 => "Contemporary Jazz",
        121 => "Contemporary Latin",
        122 => "Contemporary R&B",
        123 => "Contemporary Singer/Songwriter",
        124 => "Cool",
        125 => "Country",
        126 => "Country Blues",
        127 => "Country Gospel",
        128 => "Coupé-Décalé",
        129 => "Crossover Jazz",
        130 => "Cuban",
        131 => "Dabke",
        132 => "Dance",
        133 => "Dangdut",
        134 => "Death Metal/Black Metal",
        135 => "Delta Blues",
        136 => "Devotional & Spiritual",
        137 => "Dini",
        138 => "Dirty South",
        139 => "Disco",
        140 => "Disney",
        141 => "Dixieland",
        142 => "Doo Wop",
        143 => "Downtempo",
        144 => "Dub",
        145 => "Dubstep",
        146 => "EMO",
        147 => "Early Music",
        148 => "East Coast Rap",
        149 => "Easter",
        150 => "Easy Listening",
        151 => "Egyptian Hip-Hop",
        152 => "Egyptian Pop",
        153 => "Egyptian Tarab",
        154 => "Electric Blues",
        155 => "Electro-Cha'abi",
        156 => "Electronic",
        157 => "Electronica",
        158 => "Enka",
        159 => "Europe",
        160 => "Fado",
        161 => "Fantezi",
        162 => "Farsi",
        163 => "Film Soundtrack",
        164 => "Fitness & Workout",
        165 => "Flamenco",
        166 => "Folk",
        167 => "Folk-Rock",
        168 => "Foreign Cinema",
        169 => "Forró",
        170 => "France",
        171 => "French Pop",
        172 => "Frevo",
        173 => "Funk",
        174 => "Fusion",
        175 => "Gangsta Rap",
        176 => "Garage",
        177 => "German Folk",
        178 => "German Pop",
        179 => "Ghazals",
        180 => "Glam Rock",
        181 => "Gospel",
        182 => "Goth Rock",
        183 => "Gqom",
        184 => "Grunge",
        185 => "Guajira",
        186 => "Guaracha",
        187 => "Guitar",
        188 => "Gujarati",
        189 => "Hair Metal",
        190 => "Halk",
        191 => "Halloween",
        192 => "Hard Bop",
        193 => "Hard Rock",
        194 => "Hardcore",
        195 => "Hardcore Rap",
        196 => "Haryanvi",
        197 => "Hawaii",
        198 => "Healing",
        199 => "Heavy Metal",
        200 => "Highlife",
        201 => "Hindustani Classical",
        202 => "Hip Hop/Rap",
        203 => "Hip-Hop",
        204 => "Holiday",
        205 => "Honky Tonk",
        206 => "House",
        207 => "Hörspiele",
        208 => "IDM/Experimental",
        209 => "Iberia",
        210 => "Impressionist",
        211 => "Indian",
        212 => "Indian Classical",
        213 => "Indian Folk",
        214 => "Indian Pop",
        215 => "Indie Egyptian",
        216 => "Indie Levant",
        217 => "Indie Maghreb",
        218 => "Indie Pop",
        219 => "Indie Rock",
        220 => "Indo Pop",
        221 => "Indonesian Religious",
        222 => "Industrial",
        223 => "Inspirational",
        224 => "Instrumental",
        225 => "Iraqi Folk",
        226 => "Iraqi Pop",
        227 => "Iraqi Tarab",
        228 => "Islamic",
        229 => "Israeli",
        230 => "J-Pop",
        231 => "Jam Bands",
        232 => "Japan",
        233 => "Jazz",
        234 => "Jungle/Drum'n'bass",
        235 => "K-Pop",
        236 => "Kannada",
        237 => "Karaoke",
        238 => "Kayokyoku",
        239 => "Khaleeji",
        240 => "Khaleeji Folk",
        241 => "Khaleeji Hip-Hop",
        242 => "Khaleeji Jalsat",
        243 => "Khaleeji Pop",
        244 => "Khaleeji Shailat",
        245 => "Khaleeji Tarab",
        246 => "Kizomba",
        247 => "Klezmer",
        248 => "Korean",
        249 => "Korean Folk-Pop",
        250 => "Korean Hip-Hop",
        251 => "Korean Indie",
        252 => "Korean Rock",
        253 => "Korean Traditional",
        254 => "Kuduro",
        255 => "Kwaito",
        256 => "Latin",
        257 => "Latin Jazz",
        258 => "Latin Rap",
        259 => "Levant",
        260 => "Levant Electronic",
        261 => "Levant Hip-Hop",
        262 => "Levant Pop",
        263 => "Lounge",
        264 => "Lovers Rock",
        265 => "Lullabies",
        266 => "MPB",
        267 => "Maghreb Dance",
        268 => "Maghreb Electronic",
        269 => "Maghreb Hip-Hop",
        270 => "Maghreb Pop",
        271 => "Maghreb Rai",
        272 => "Mainstream Jazz",
        273 => "Malayalam",
        274 => "Malaysian Pop",
        275 => "Mambo",
        276 => "Mandopop",
        277 => "Manila Sound",
        278 => "Marathi",
        279 => "Marching Bands",
        280 => "Maskandi",
        281 => "Mbalax",
        282 => "Medieval Era",
        283 => "Meditation",
        284 => "Minimalism",
        285 => "Modern Era",
        286 => "Motown",
        287 => "Musicals",
        288 => "Nature",
        289 => "Ndombolo",
        290 => "Neo-Soul",
        291 => "New Acoustic",
        292 => "New Age",
        293 => "New Wave",
        294 => "North African",
        295 => "North America",
        296 => "Novelty",
        297 => "Odia",
        298 => "Old School Rap",
        299 => "Oldies",
        300 => "Operaa",
        301 => "Opera",
        302 => "Oratorio",
        303 => "Orchestral",
        304 => "Original Pilipino Music",
        305 => "Original Score",
        306 => "Outlaw Country",
        307 => "Pagode",
        308 => "Percussion",
        309 => "Piano",
        310 => "Pinoy Pop",
        311 => "Polka",
        312 => "Pop",
        313 => "Pop Punk",
        314 => "Pop in Spanish",
        315 => "Pop/Rock",
        316 => "Praise & Worship",
        317 => "Prog-Rock/Art Rock",
        318 => "Psychedelic",
        319 => "Punjabi",
        320 => "Punjabi Pop",
        321 => "Punk",
        322 => "R&B/Soul",
        323 => "Rabindra Sangeet",
        324 => "Ragtime",
        325 => "Raices",
        326 => "Rajasthani",
        327 => "Rap",
        328 => "Reggae",
        329 => "Reggaeton / Latin Urban",
        330 => "Regional Indian",
        331 => "Regional Mexicano",
        332 => "Relaxation",
        333 => "Religious",
        334 => "Renaissance",
        335 => "Rock",
        336 => "Rock & Roll",
        337 => "Rockabilly",
        338 => "Romantic Era",
        339 => "Roots Reggae",
        340 => "Roots Rock",
        341 => "Russian",
        342 => "Russian Bard",
        343 => "Russian Chanson",
        344 => "Russian Hip-Hop",
        345 => "Russian Pop",
        346 => "Russian Rock",
        347 => "Russian Romance",
        348 => "Sacred",
        349 => "Salsa y Tropical",
        350 => "Samba",
        351 => "Sanat",
        352 => "Sertanejo",
        353 => "Shangaan Electro",
        354 => "Shows",
        355 => "Sing-Along",
        356 => "Singer/Songwriter",
        357 => "Ska",
        358 => "Smooth Jazz",
        359 => "Soca",
        360 => "Soft Rock",
        361 => "Solo Instrumental",
        362 => "Son",
        363 => "Soukous",
        364 => "Soul",
        365 => "Sound Effects",
        366 => "Soundtrack",
        367 => "South Africa",
        368 => "South America",
        369 => "Southern Gospel",
        370 => "Southern Rock",
        371 => "Spoken Word",
        372 => "Standards",
        373 => "Standup Comedy",
        374 => "Stories",
        375 => "Sufi",
        376 => "Surf",
        377 => "Swing",
        378 => "TV Soundtrack",
        379 => "Taarab",
        380 => "Tai-Pop",
        381 => "Taiwanese Folk",
        382 => "Tamil",
        383 => "Tango",
        384 => "Tarab",
        385 => "Techno",
        386 => "Teen Pop",
        387 => "Telugu",
        388 => "Tex-Mex",
        389 => "Thai Country",
        390 => "Thai Pop",
        391 => "Thanksgiving",
        392 => "Tibetan Native Music",
        393 => "Timba",
        394 => "Trad Jazz",
        395 => "Traditional Bluegrass",
        396 => "Traditional Celtic",
        397 => "Traditional Country",
        398 => "Traditional Folk",
        399 => "Traditional Gospel",
        400 => "Traditional Pop",
        401 => "Trance",
        402 => "Travel",
        403 => "Trot",
        404 => "Turkish",
        405 => "Turkish Alternative",
        406 => "Turkish Hip-Hop/Rap",
        407 => "Turkish Pop",
        408 => "Turkish Rock",
        409 => "UK Hip Hop",
        410 => "Underground Rap",
        411 => "Urban Cowboy",
        412 => "Urdu",
        413 => "Video Game",
        414 => "Violin",
        415 => "Vocal",
        416 => "Vocal Jazz",
        417 => "Vocal Pop",
        418 => "Wedding Music",
        419 => "West Coast Rap",
        420 => "World",
        421 => "Worldbeat",
        422 => "Yoga",
        423 => "Zouglou",
        424 => "Özgün",


    ],


    // 'genres' =>  [

    //     [1] => (Classical) Orchestral
    // [2] => (Jazz) Latin Jazz
    // [3] => (Rock) Singer/Songwriter
    // [4] => Acoustic Blues
    // [5] => Adult Alternative
    // [6] => Adult Contemporary
    // [7] => African
    // [8] => African Dancehall
    // [9] => African Reggae
    // [10] => Afrikaans
    // [11] => Afro House
    // [12] => Afro Soul
    // [13] => Afro-Beat
    // [14] => Afro-Pop
    // [15] => Afro-folk
    // [16] => Afro-fusion
    // [17] => Afrobeats
    // [18] => Alte
    // [19] => Alternative
    // [20] => Alternative &amp; Rock in Spanish
    // [21] => Alternative Country
    // [22] => Alternative Folk
    // [23] => Alternative Rap
    // [24] => Amapiano
    // [25] => Ambient
    // [26] => American Trad Rock
    // [27] => Americana
    // [28] => Anime
    // [29] => Arabesque
    // [30] => Arabic
    // [31] => Arabic Pop
    // [32] => Arena Rock
    // [33] => Art Song
    // [34] => Asia
    // [35] => Assamese
    // [36] => Australia
    // [37] => Avant-Garde
    // [38] => Avant-Garde Jazz
    // [39] => Axé
    // [40] => Baile Funk
    // [41] => Baladas y Boleros
    // [42] => Baroque Era
    // [43] => Bass
    // [44] => Bebop
    // [45] => Benga
    // [46] => Bengali
    // [47] => Bhojpuri
    // [48] => Big Band
    // [49] => Bluegrass
    // [50] => Blues
    // [51] => Blues-Rock
    // [52] => Bolero
    // [53] => Bollywood
    // [54] => Bongo-Flava
    // [55] => Bossa Nova
    // [56] => Brass &amp; Woodwinds
    // [57] => Brazilian
    // [58] => Breakbeat
    // [59] => British Invasion
    // [60] => Britpop
    // [61] => CCM
    // [62] => Cajun
    // [63] => Calypso
    // [64] => Cantata
    // [65] => Cantopop
    // [66] => Caribbean
    // [67] => Carnatic Classical
    // [68] => Cello
    // [69] => Celtic
    // [70] => Celtic Folk
    // [71] => Chachacha
    // [72] => Chamber Music
    // [73] => Chant
    // [74] => Chanukah
    // [75] => Chicago Blues
    // [76] => Children's Music
    // [77] => Chinese
    // [78] => Chinese Alt
    // [79] => Chinese Classical
    // [80] => Chinese Flute
    // [81] => Chinese Hip-Hop
    // [82] => Chinese Opera
    // [83] => Chinese Orchestral
    // [84] => Chinese Regional Folk
    // [85] => Chinese Rock
    // [86] => Chinese Strings
    // [87] => Choral
    // [88] => Choro
    // [89] => Christian &amp; Gospel
    // [90] => Christian Metal
    // [91] => Christian Pop
    // [92] => Christian Rap
    // [93] => Christian Rock
    // [94] => Christmas
    // [95] => Christmas: Children's
    // [96] => Christmas: Classic
    // [97] => Christmas: Classical
    // [98] => Christmas: Country
    // [99] => Christmas: Jazz
    // [100] => Christmas: Modern
    // [101] => Christmas: Pop
    // [102] => Christmas: R&amp;B
    // [103] => Christmas: Religious
    // [104] => Christmas: Rock
    // [105] => Classic Blues
    // [106] => Classic Christian
    // [107] => Classic/Modern Dancehall
    // [108] => Classical
    // [109] => Classical Crossover
    // [110] => Classical Era
    // [111] => College Rock
    // [112] => Comedy
    // [113] => Contemporary Bluegrass
    // [114] => Contemporary Blues
    // [115] => Contemporary Celtic
    // [116] => Contemporary Country
    // [117] => Contemporary Era
    // [118] => Contemporary Folk
    // [119] => Contemporary Gospel
    // [120] => Contemporary Jazz
    // [121] => Contemporary Latin
    // [122] => Contemporary R&amp;B
    // [123] => Contemporary Singer/Songwriter
    // [124] => Cool
    // [125] => Country
    // [126] => Country Blues
    // [127] => Country Gospel
    // [128] => Coupé-Décalé
    // [129] => Crossover Jazz
    // [130] => Cuban
    // [131] => Dabke
    // [132] => Dance
    // [133] => Dangdut
    // [134] => Death Metal/Black Metal
    // [135] => Delta Blues
    // [136] => Devotional &amp; Spiritual
    // [137] => Dini
    // [138] => Dirty South
    // [139] => Disco
    // [140] => Disney
    // [141] => Dixieland
    // [142] => Doo Wop
    // [143] => Downtempo
    // [144] => Dub
    // [145] => Dubstep
    // [146] => EMO
    // [147] => Early Music
    // [148] => East Coast Rap
    // [149] => Easter
    // [150] => Easy Listening
    // [151] => Egyptian Hip-Hop
    // [152] => Egyptian Pop
    // [153] => Egyptian Tarab
    // [154] => Electric Blues
    // [155] => Electro-Cha'abi
    // [156] => Electronic
    // [157] => Electronica
    // [158] => Enka
    // [159] => Europe
    // [160] => Fado
    // [161] => Fantezi
    // [162] => Farsi
    // [163] => Film Soundtrack
    // [164] => Fitness &amp; Workout
    // [165] => Flamenco
    // [166] => Folk
    // [167] => Folk-Rock
    // [168] => Foreign Cinema
    // [169] => Forró
    // [170] => France
    // [171] => French Pop
    // [172] => Frevo
    // [173] => Funk
    // [174] => Fusion
    // [175] => Gangsta Rap
    // [176] => Garage
    // [177] => German Folk
    // [178] => German Pop
    // [179] => Ghazals
    // [180] => Glam Rock
    // [181] => Gospel
    // [182] => Goth Rock
    // [183] => Gqom
    // [184] => Grunge
    // [185] => Guajira
    // [186] => Guaracha
    // [187] => Guitar
    // [188] => Gujarati
    // [189] => Hair Metal
    // [190] => Halk
    // [191] => Halloween
    // [192] => Hard Bop
    // [193] => Hard Rock
    // [194] => Hardcore
    // [195] => Hardcore Rap
    // [196] => Haryanvi
    // [197] => Hawaii
    // [198] => Healing
    // [199] => Heavy Metal
    // [200] => Highlife
    // [201] => Hindustani Classical
    // [202] => Hip Hop/Rap
    // [203] => Hip-Hop
    // [204] => Holiday
    // [205] => Honky Tonk
    // [206] => House
    // [207] => Hörspiele
    // [208] => IDM/Experimental
    // [209] => Iberia
    // [210] => Impressionist
    // [211] => Indian
    // [212] => Indian Classical
    // [213] => Indian Folk
    // [214] => Indian Pop
    // [215] => Indie Egyptian
    // [216] => Indie Levant
    // [217] => Indie Maghreb
    // [218] => Indie Pop
    // [219] => Indie Rock
    // [220] => Indo Pop
    // [221] => Indonesian Religious
    // [222] => Industrial
    // [223] => Inspirational
    // [224] => Instrumental
    // [225] => Iraqi Folk
    // [226] => Iraqi Pop
    // [227] => Iraqi Tarab
    // [228] => Islamic
    // [229] => Israeli
    // [230] => J-Pop
    // [231] => Jam Bands
    // [232] => Japan
    // [233] => Jazz
    // [234] => Jungle/Drum'n'bass
    // [235] => K-Pop
    // [236] => Kannada
    // [237] => Karaoke
    // [238] => Kayokyoku
    // [239] => Khaleeji
    // [240] => Khaleeji Folk
    // [241] => Khaleeji Hip-Hop
    // [242] => Khaleeji Jalsat
    // [243] => Khaleeji Pop
    // [244] => Khaleeji Shailat
    // [245] => Khaleeji Tarab
    // [246] => Kizomba
    // [247] => Klezmer
    // [248] => Korean
    // [249] => Korean Folk-Pop
    // [250] => Korean Hip-Hop
    // [251] => Korean Indie
    // [252] => Korean Rock
    // [253] => Korean Traditional
    // [254] => Kuduro
    // [255] => Kwaito
    // [256] => Latin
    // [257] => Latin Jazz
    // [258] => Latin Rap
    // [259] => Levant
    // [260] => Levant Electronic
    // [261] => Levant Hip-Hop
    // [262] => Levant Pop
    // [263] => Lounge
    // [264] => Lovers Rock
    // [265] => Lullabies
    // [266] => MPB
    // [267] => Maghreb Dance
    // [268] => Maghreb Electronic
    // [269] => Maghreb Hip-Hop
    // [270] => Maghreb Pop
    // [271] => Maghreb Rai
    // [272] => Mainstream Jazz
    // [273] => Malayalam
    // [274] => Malaysian Pop
    // [275] => Mambo
    // [276] => Mandopop
    // [277] => Manilla Sound
    // [278] => Marathi
    // [279] => Marching Bands
    // [280] => Maskandi
    // [281] => Mbalax
    // [282] => Medieval Era
    // [283] => Meditation
    // [284] => Minimalism
    // [285] => Modern Era
    // [286] => Motown
    // [287] => Musicals
    // [288] => Nature
    // [289] => Ndombolo
    // [290] => Neo-Soul
    // [291] => New Acoustic
    // [292] => New Age
    // [293] => New Wave
    // [294] => North African
    // [295] => North America
    // [296] => Novelty
    // [297] => Odia
    // [298] => Old School Rap
    // [299] => Oldies
    // [300] => Opera
    // [301] => Oratorio
    // [302] => Orchestral
    // [303] => Original Pilipino Music
    // [304] => Original Score
    // [305] => Outlaw Country
    // [306] => Pagode
    // [307] => Percussion
    // [308] => Piano
    // [309] => Pinoy Pop
    // [310] => Polka
    // [311] => Pop
    // [312] => Pop Punk
    // [313] => Pop in Spanish
    // [314] => Pop/Rock
    // [315] => Praise &amp; Worship
    // [316] => Prog-Rock/Art Rock
    // [317] => Psychedelic
    // [318] => Punjabi
    // [319] => Punjabi Pop
    // [320] => Punk
    // [321] => R&amp;B/Soul
    // [322] => Rabindra Sangeet
    // [323] => Ragtime
    // [324] => Raices
    // [325] => Rajasthani
    // [326] => Rap
    // [327] => Reggae
    // [328] => Reggaeton / Latin Urban
    // [329] => Regional Indian
    // [330] => Regional Mexicano
    // [331] => Relaxation
    // [332] => Religious
    // [333] => Renaissance
    // [334] => Rock
    // [335] => Rock &amp; Roll
    // [336] => Rockabilly
    // [337] => Romantic Era
    // [338] => Roots Reggae
    // [339] => Roots Rock
    // [340] => Russian
    // [341] => Russian Bard
    // [342] => Russian Chanson
    // [343] => Russian Hip-Hop
    // [344] => Russian Pop
    // [345] => Russian Rock
    // [346] => Russian Romance
    // [347] => Sacred
    // [348] => Salsa y Tropical
    // [349] => Samba
    // [350] => Sanat
    // [351] => Sertanejo
    // [352] => Shangaan Electro
    // [353] => Shows
    // [354] => Sing-Along
    // [355] => Singer/Songwriter
    // [356] => Ska
    // [357] => Smooth Jazz
    // [358] => Soca
    // [359] => Soft Rock
    // [360] => Solo Instrumental
    // [361] => Son
    // [362] => Soukous
    // [363] => Soul
    // [364] => Sound Effects
    // [365] => Soundtrack
    // [366] => South Africa
    // [367] => South America
    // [368] => Southern Gospel
    // [369] => Southern Rock
    // [370] => Spoken Word
    // [371] => Standards
    // [372] => Standup Comedy
    // [373] => Stories
    // [374] => Sufi
    // [375] => Surf
    // [376] => Swing
    // [377] => TV Soundtrack
    // [378] => Taarab
    // [379] => Tai-Pop
    // [380] => Taiwanese Folk
    // [381] => Tamil
    // [382] => Tango
    // [383] => Tarab
    // [384] => Techno
    // [385] => Teen Pop
    // [386] => Telugu
    // [387] => Tex-Mex
    // [388] => Thai Country
    // [389] => Thai Pop
    // [390] => Thanksgiving
    // [391] => Tibetan Native Music
    // [392] => Timba
    // [393] => Trad Jazz
    // [394] => Traditional Bluegrass
    // [395] => Traditional Celtic
    // [396] => Traditional Country
    // [397] => Traditional Folk
    // [398] => Traditional Gospel
    // [399] => Traditional Pop
    // [400] => Trance
    // [401] => Travel
    // [402] => Trot
    // [403] => Turkish
    // [404] => Turkish Alternative
    // [405] => Turkish Hip-Hop/Rap
    // [406] => Turkish Pop
    // [407] => Turkish Rock
    // [408] => UK Hip Hop
    // [409] => Underground Rap
    // [410] => Urban Cowboy
    // [411] => Urdu
    // [412] => Video Game
    // [413] => Violin
    // [414] => Vocal
    // [415] => Vocal Jazz
    // [416] => Vocal Pop
    // [417] => Wedding Music
    // [418] => West Coast Rap
    // [419] => World
    // [420] => Worldbeat
    // [421] => Yoga
    // [422] => Zouglou
    // [423] => Zydeco
    // [424] => Özgün

    // ],
];
